#Launch configuration
#Sat Sep 20 13:08:13 JST 2025
EEW1ShindoMin=0
EEW1ShindoMinLoc=0
EEW2ShindoMinLoc=0
EEW2ShindoMinNat=0
EQInfoIntensity=1
advancedEEW=false
alwaysOnTop=false
bg=51;52;57
currentVersion=1.8.5
displayChoice=2
displayChoiceSub=3
displayCityNames=true
displayEQScrollBar=true
displayMiniMap=true
displayPrefList=true
eqSpeakerChoice=1
firstOpen=false
fixedMode=false
fontColor=255;255;255
forceForecastOnDeep=false
gameMode=false
homeViewNW=45.62207;126.89925
homeViewSE=29.92448;146.10139
includeUserInZoom=false
intensityIcon=true
interfaceDisplayChoice=0
interfaceDisplayChoiceSub=0
interfaceScale=1.00000
langChoice=0
level0ShindoIndex=4
level1PGAIndex=2
level1ShindoIndex=2
level2PGAIndex=5
level2ShindoIndex=2
localEEW1=false
localEEW2=false
localPGA1=false
localPGA1Radius=75.00000
localPGA2=false
localPGA2Radius=120.00000
localShindo0=false
localShindo0Radius=45.00000
localShindo1=false
localShindo1Radius=60.00000
localShindo2=false
localShindo2Radius=115.00000
mapBg=31;32;37
mapScale=1.00000
mute=false
openOnStartup=true
persistentMode=true
polyColor=63;64;69
popEEW1=true
popEEW2=true
popPGA1=true
popPGA2=true
popShindo0=true
popShindo1=true
popShindo2=true
resetViewAfterEvent=true
roundRectangles=true
serverChoice=0
showClosestSation=true
showTsunami=true
soundEEW1=true
soundEEW2=true
soundEQInfo=true
soundPGA1=true
soundPGA2=true
soundPeripheral=0
soundShindo0=true
soundShindo1=true
soundShindo2=true
soundTsunami=true
teleseismicSound=true
tsunamiBrowser=true
tsunamiChoice=0
useShindoColor=true
useSmallIcons=false
useSystemProxy=true
userLatitude=<USER_LATITUDE>
userLongitude=<USER_LONGITUDE>
userVisible=true
volume=-3.00000
wakeUpScreen=true
winChoice=0
zoomEEW1=6
zoomEEW2=6
zoomPGA1=6
zoomPGA2=6
zoomShindo0=6
zoomShindo1=6
zoomShindo2=6
