title   Arch Linux
linux   /vmlinuz-linux-lts
initrd  /intel-ucode.img
initrd  /initramfs-linux-lts.img
options	cryptdevice=UUID=<LUKS_PARTITION_UUID>:arch_cryptroot root=/dev/mapper/arch_cryptroot rw rd.luks.options=discard quiet loglevel=3

