@version: 4.12
@include "scl.conf"

source s_journal { systemd-journal(); };
destination d_graylog {
  graylog2(
    host("<GRAYLOG_SERVER>") port(12201) transport(tcp)
    template("$(format-json --auto-cast --omit-empty-values
      version='1.1' host='${HOST:--}' short_message='${MSG:--}'
      level=int(${LEVEL_NUM}) timestamp=int64(${R_UNIXTIME})
      _program='${PROGRAM}' _pid=int(${PID}) _facility='${FACILITY}'
      _systemd_unit='${.journald._SYSTEMD_UNIT}'
      _systemd_user_unit='${.journald._SYSTEMD_USER_UNIT}'
      _transport='${.journald._TRANSPORT}'
      _comm='${.journald._COMM}'
      _boot_id='${.journald._BOOT_ID}')$(binary 0x00)")
  );
};
log { source(s_journal); destination(d_graylog); };
